### ISSUE TITLE
关于文件结构的几点建议

### ISSUE THREAD

**Issue by BKGiser** [BkGoup/LeafletFramework#1]
### 关于文件结构的几点建议
* **nodeServerForConfWeb** 这个文件夹的名字是不是有一点长啊!!!
* gisDemo 这个文件夹如果从 **tempory** 这个文件夹中拿出来会不会比较好，因为当初设计 tempory 这个文件夹就是为了放一下零时存放的东西的，开始本来都没打算提交上去的

**Comment by hanguang90** [comment]
已经修改，并提交到qizhi-refactor。
